version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/'

services:
  currency-exchange: 
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network:
    