version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/'

services:
  zipkin-server: 
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports: 
      - "9411:9411"
    networks:
      - currency-network
    depends_on:  
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      
  rabbitmq: 
    image: rabbitmq:3.11.4-management
    mem_limit: 300m
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network
            
  api-gateway: 
    image: in28min/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka  
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/    
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit  
      
  currency-converison: 
    image: in28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
#      - spring-cloud-config-server
      - rabbitmq
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit        

  currency-exchange: 
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
#      - spring-cloud-config-server
#      - rabbitmq
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
#  limits-service: 
#    image: in28min/mmv2-limits-service:0.0.1-SNAPSHOT
#    mem_limit: 700m
#    ports: 
#      - "7800:7800"
#    networks:
#      - currency-network
#    depends_on:
#      - naming-server
#      - spring-cloud-config-server
#      - rabbitmq
#    environment: 
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
#      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888 
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit   
      
#  spring-cloud-config-server: 
#    image: in28min/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
#    mem_limit: 700m
#    ports: 
#      - "8888:8888"
#    networks:
#      - currency-network
#    depends_on:
#      - naming-server
#      - rabbitmq
#    environment: 
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/      
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit        
      
  naming-server: 
    image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8761:8761"
    networks:
      - currency-network    

networks:
  currency-network:
    