version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/'

services:
  zipkin-server: 
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports: 
      - "9411:9411"
    networks:
      - currency-network
      
  api-gateway: 
    image: in28min/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka  
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/    

  currency-converison: 
    image: in28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
      - spring-cloud-config-server
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888
      

  currency-exchange: 
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - spring-cloud-config-server
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888
      
  limits-service: 
    image: in28min/mmv2-limits-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "7800:7800"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - spring-cloud-config-server
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-cloud-config-server:8888    
      
  spring-cloud-config-server: 
    image: in28min/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8888:8888"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/      
      
  naming-server: 
    image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8761:8761"
    networks:
      - currency-network    

networks:
  currency-network:
    