spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://localhost:8888
# "spring.cloud.config.profile" will override "spring.profiles.active""
  profiles:
    active: dev
  cloud:
    config:
      profile: qa
  sleuth:
    sampler:
      probability: 1.0 #where 0.05=5%, 1.0=100% (% of request being trace)         
    
server:
  port: 7800   
    
limits-service:
  minimum: 3
  maximum: 997
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
# Actuator:      
management: 
  endpoints:
    web:
      exposure:
        include: "*"