spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888    
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0 #where 0.05=5%, 1.0=100% (% of request being trace)

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://naming-server:8761/eureka
     
# Actuator:      
management: 
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  retry:
    instances:
      sample-api:
        #maxRetryAttempts: 5
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPEriod: 1s
  bulkhead:
    instamces:
      default:
        maxConcurrentCslls: 10
      sample-api:
        maxConcurrentCslls: 10
      